export interface SDAPIOptions {
    samples_save: boolean
    samples_format: string
    samples_filename_pattern: string
    save_images_add_number: boolean
    grid_save: boolean
    grid_format: string
    grid_extended_filename: boolean
    grid_only_if_multiple: boolean
    grid_prevent_empty_spots: boolean
    n_rows: number
    enable_pnginfo: boolean
    save_txt: boolean
    save_images_before_face_restoration: boolean
    save_images_before_highres_fix: boolean
    save_images_before_color_correction: boolean
    jpeg_quality: number
    export_for_4chan: boolean
    use_original_name_batch: boolean
    use_upscaler_name_as_suffix: boolean
    save_selected_only: boolean
    do_not_add_watermark: boolean
    temp_dir: string
    clean_temp_dir_at_start: boolean
    outdir_samples: string
    outdir_txt2img_samples: string
    outdir_img2img_samples: string
    outdir_extras_samples: string
    outdir_grids: string
    outdir_txt2img_grids: string
    outdir_img2img_grids: string
    outdir_save: string
    save_to_dirs: boolean
    grid_save_to_dirs: boolean
    use_save_to_dirs_for_ui: boolean
    directories_filename_pattern: string
    directories_max_prompt_words: number
    ESRGAN_tile: number
    ESRGAN_tile_overlap: number
    realesrgan_enabled_models: string[]
    upscaler_for_img2img: null
    use_scale_latent_for_hires_fix: boolean
    face_restoration_model: null
    code_former_weight: number
    face_restoration_unload: boolean
    memmon_poll_rate: number
    samples_log_stdout: boolean
    multiple_tqdm: boolean
    unload_models_when_training: boolean
    pin_memory: boolean
    save_optimizer_state: boolean
    dataset_filename_word_regex: string
    dataset_filename_join_string: string
    training_image_repeats_per_epoch: number
    training_write_csv_every: number
    training_xattention_optimizations: boolean
    sd_model_checkpoint: string
    sd_checkpoint_cache: number
    sd_vae: string
    sd_vae_as_default: boolean
    sd_hypernetwork: string
    sd_hypernetwork_strength: number
    inpainting_mask_weight: number
    initial_noise_multiplier: number
    img2img_color_correction: boolean
    img2img_fix_steps: boolean
    img2img_background_color: string
    enable_quantization: boolean
    enable_emphasis: boolean
    use_old_emphasis_implementation: boolean
    enable_batch_seeds: boolean
    comma_padding_backtrack: number
    CLIP_stop_at_last_layers: number
    random_artist_categories: any[]
    interrogate_keep_models_in_memory: boolean
    interrogate_use_builtin_artists: boolean
    interrogate_return_ranks: boolean
    interrogate_clip_num_beams: number
    interrogate_clip_min_length: number
    interrogate_clip_max_length: number
    interrogate_clip_dict_limit: number
    interrogate_deepbooru_score_threshold: number
    deepbooru_sort_alpha: boolean
    deepbooru_use_spaces: boolean
    deepbooru_escape: boolean
    deepbooru_filter_tags: string
    show_progressbar: boolean
    show_progress_every_n_steps: number
    show_progress_type: string
    show_progress_grid: boolean
    return_grid: boolean
    do_not_show_images: boolean
    add_model_hash_to_info: boolean
    add_model_name_to_info: boolean
    disable_weights_auto_swap: boolean
    send_seed: boolean
    send_size: boolean
    font: string
    js_modal_lightbox: boolean
    js_modal_lightbox_initially_zoomed: boolean
    show_progress_in_title: boolean
    quicksettings: string
    localization: string
    hide_samplers: any[]
    eta_ddim: number
    eta_ancestral: number
    ddim_discretize: string
    s_churn: number
    s_tmin: number
    s_noise: number
    eta_noise_seed_delta: number
    disabled_extensions: string[]
}
