name: 'Build Image'

on:
  push:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: 'ghcr.io'
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Prepare Image Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: 'ghcr.io/${{ github.repository_owner }}/stable-journey-bot'
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build Image & Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'
